spring.application.name=cordo

spring.datasource.url=jdbc:postgresql://localhost:5454/DataBase
spring.datasource.username=postgres
spring.datasource.password=41424344
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ???????? FLYWAY (???? 5454, ??? DataBase)
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5454/DataBase
spring.flyway.user=postgres
spring.flyway.password=41424344

spring.data.redis.host=localhost
spring.data.redis.port=6379

user.start-balance=8
