spring.application.name=cordo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5454/DataBase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:41424344}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#jdbc:postgresql://localhost:5454/DataBase
# ???????? FLYWAY (???? 5454, ??? DataBase)
spring.flyway.enabled=true
spring.flyway.url= jdbc:postgresql://postgres:5432/DataBase
spring.flyway.user=postgres
spring.flyway.password=41424344

spring.flyway.repair-on-migrate=true
user.start-balance=8